env:
  browser: true
  es6: true
  node: true,
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: off
ignorePatterns:
  - "!src/**/*"
globals:
  Logger: readonly
